// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[licenses]]
= License Information


[[sec:gradle_documentation]]
== Gradle Documentation

_Copyright © 2007-2018 Gradle, Inc._

Gradle build tool source code is open-source and licensed under the link:https://github.com/gradle/gradle/blob/master/LICENSE[Apache License 2.0].


Gradle user manual and DSL references are licensed under link:http://creativecommons.org/licenses/by-nc-sa/4.0/[Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License].


[[licenses:build_scan_plugin]]
== Gradle Build Scan Plugin

Use of the link:https://scans.gradle.com/plugin/[build scan plugin] is subject to link:https://gradle.com/legal/terms-of-service/[Gradle's Terms of Service].


[[licenses:plugin_publish_plugin]]
== Gradle Plugin Publish Plugin

The link:https://plugins.gradle.org/docs/publish-plugin[Plugin Publish Plugin] is licensed under the link:https://www.apache.org/licenses/LICENSE-2.0.html[Apache License 2.0].


[[licenses:plugin_portal_marker_poms]]
== Gradle Plugin Portal Marker POM Files

Marker POM files generated by the link:https://plugins.gradle.org[Gradle Plugin Portal] to allow resolving plugins using the `plugins {}` block are licensed under the link:https://www.apache.org/licenses/LICENSE-2.0.html[Apache License 2.0].


[[licenses:gradle_completion]]
== Gradle Completion

Command-line link:https://github.com/gradle/gradle-completion[completion scripts for Gradle] are open-source and licensed under the link:https://raw.githubusercontent.com/gradle/gradle-completion/master/LICENSE[MIT License].
